title: Jumaane Pond’s Active Directory Security Monitoring Lab
description: Active Directory Threat Detection & SIEM Analysis with Splunk
show_downloads: false
google_analytics:
theme: jekyll-theme-midnight
